-- schema.supabase.sql
-- Generated from Laravel migrations in database/migrations
-- Target: Supabase (PostgreSQL)
-- Date: 2025-12-16
--
-- Notes:
-- - This is a schema-only export (tables, constraints, indexes).
-- - It does NOT include data.
-- - If you already ran migrations in Supabase, running this again may error due to existing objects.
-- - Laravel's `enum()` becomes a CHECK constraint in Postgres.
-- - Column order modifiers like `->after()` are ignored in Postgres.

BEGIN;

-- Optional reset (commented out by default):
-- DROP TABLE IF EXISTS role_has_permissions CASCADE;
-- DROP TABLE IF EXISTS user_has_roles CASCADE;
-- DROP TABLE IF EXISTS playlist_project CASCADE;
-- DROP TABLE IF EXISTS project_likes CASCADE;
-- DROP TABLE IF EXISTS follows CASCADE;
-- DROP TABLE IF EXISTS editor_project_assets CASCADE;
-- DROP TABLE IF EXISTS editor_projects CASCADE;
-- DROP TABLE IF EXISTS user_files CASCADE;
-- DROP TABLE IF EXISTS user_storage_quotas CASCADE;
-- DROP TABLE IF EXISTS user_settings CASCADE;
-- DROP TABLE IF EXISTS notifications CASCADE;
-- DROP TABLE IF EXISTS conversation_messages CASCADE;
-- DROP TABLE IF EXISTS conversations CASCADE;
-- DROP TABLE IF EXISTS messages CASCADE;
-- DROP TABLE IF EXISTS comments CASCADE;
-- DROP TABLE IF EXISTS content_flags CASCADE;
-- DROP TABLE IF EXISTS activity_logs CASCADE;
-- DROP TABLE IF EXISTS search_histories CASCADE;
-- DROP TABLE IF EXISTS scripts CASCADE;
-- DROP TABLE IF EXISTS projects CASCADE;
-- DROP TABLE IF EXISTS channels CASCADE;
-- DROP TABLE IF EXISTS categories CASCADE;
-- DROP TABLE IF EXISTS permissions CASCADE;
-- DROP TABLE IF EXISTS roles CASCADE;
-- DROP TABLE IF EXISTS personal_access_tokens CASCADE;
-- DROP TABLE IF EXISTS failed_jobs CASCADE;
-- DROP TABLE IF EXISTS password_resets CASCADE;
-- DROP TABLE IF EXISTS users CASCADE;

-- Core
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    username VARCHAR(255) NULL,
    email VARCHAR(255) NOT NULL,
    position VARCHAR(255) NULL,
    tags JSONB NULL,
    avatar_url VARCHAR(255) NULL,
    banner_url VARCHAR(255) NULL,
    pen_name VARCHAR(255) NULL,
    studio_name VARCHAR(255) NULL,
    bio TEXT NULL,
    headline VARCHAR(255) NULL,
    location VARCHAR(255) NULL,
    website VARCHAR(255) NULL,
    social_links JSONB NULL,
    contact_number VARCHAR(255) NULL,
    is_approved BOOLEAN NOT NULL DEFAULT TRUE,
    email_verified_at TIMESTAMP NULL,
    password VARCHAR(255) NOT NULL,
    remember_token VARCHAR(100) NULL,
    is_banned BOOLEAN NOT NULL DEFAULT FALSE,
    is_verified_creator BOOLEAN NOT NULL DEFAULT FALSE,
    creator_verified_at TIMESTAMP NULL,
    followers_count INTEGER NOT NULL DEFAULT 0,
    following_count INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    CONSTRAINT users_email_unique UNIQUE (email),
    CONSTRAINT users_username_unique UNIQUE (username)
);

CREATE TABLE IF NOT EXISTS password_resets (
    email VARCHAR(255) PRIMARY KEY,
    token VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NULL
);

CREATE TABLE IF NOT EXISTS failed_jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid VARCHAR(255) NOT NULL,
    connection TEXT NOT NULL,
    queue TEXT NOT NULL,
    payload TEXT NOT NULL,
    exception TEXT NOT NULL,
    failed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT failed_jobs_uuid_unique UNIQUE (uuid)
);

CREATE TABLE IF NOT EXISTS personal_access_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tokenable_type VARCHAR(255) NOT NULL,
    tokenable_id BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    token VARCHAR(64) NOT NULL,
    abilities TEXT NULL,
    last_used_at TIMESTAMP NULL,
    expires_at TIMESTAMP NULL,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    CONSTRAINT personal_access_tokens_token_unique UNIQUE (token)
);

CREATE INDEX IF NOT EXISTS personal_access_tokens_tokenable_type_tokenable_id_index
    ON personal_access_tokens (tokenable_type, tokenable_id);

-- AuthZ
CREATE TABLE IF NOT EXISTS roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    guard_name VARCHAR(255) NOT NULL DEFAULT 'web',
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    CONSTRAINT roles_name_guard_name_unique UNIQUE (name, guard_name)
);

CREATE TABLE IF NOT EXISTS permissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    guard_name VARCHAR(255) NOT NULL DEFAULT 'web',
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    CONSTRAINT permissions_name_guard_name_unique UNIQUE (name, guard_name)
);

CREATE TABLE IF NOT EXISTS user_has_roles (
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    PRIMARY KEY (user_id, role_id),
    CONSTRAINT user_has_roles_user_id_fk FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT user_has_roles_role_id_fk FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS role_has_permissions (
    permission_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    PRIMARY KEY (permission_id, role_id),
    CONSTRAINT role_has_permissions_permission_id_fk FOREIGN KEY (permission_id) REFERENCES permissions(id) ON DELETE CASCADE,
    CONSTRAINT role_has_permissions_role_id_fk FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE
);

-- Categories
CREATE TABLE IF NOT EXISTS categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    slug VARCHAR(255) NOT NULL,
    description TEXT NULL,
    icon VARCHAR(255) NULL,
    color VARCHAR(255) NOT NULL DEFAULT '#f59e0b',
    sort_order INTEGER NOT NULL DEFAULT 0,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    CONSTRAINT categories_name_unique UNIQUE (name),
    CONSTRAINT categories_slug_unique UNIQUE (slug)
);

-- Channels & chat
CREATE TABLE IF NOT EXISTS channels (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT NULL,
    category VARCHAR(255) NOT NULL DEFAULT 'General',
    allowed_role_id BIGINT NULL,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    CONSTRAINT channels_name_unique UNIQUE (name),
    CONSTRAINT channels_allowed_role_id_fk FOREIGN KEY (allowed_role_id) REFERENCES roles(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    channel_id BIGINT NOT NULL,
    body TEXT NOT NULL,
    message_type VARCHAR(255) NOT NULL DEFAULT 'text',
    attachment_data JSONB NULL,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    CONSTRAINT messages_user_id_fk FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT messages_channel_id_fk FOREIGN KEY (channel_id) REFERENCES channels(id) ON DELETE CASCADE
);

-- Projects
CREATE TABLE IF NOT EXISTS projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT NULL,
    directors_note TEXT NULL,
    video_url VARCHAR(255) NOT NULL,
    thumbnail_url VARCHAR(255) NULL,
    status VARCHAR(255) NOT NULL DEFAULT 'published',
    visibility VARCHAR(255) NOT NULL DEFAULT 'private',
    moderation_status VARCHAR(255) NOT NULL DEFAULT 'pending',
    views_count BIGINT NOT NULL DEFAULT 0,
    category VARCHAR(255) NULL,
    category_id BIGINT NULL,
    duration INTEGER NULL,
    release_year SMALLINT NULL,
    content_rating VARCHAR(10) NULL,
    language VARCHAR(50) NOT NULL DEFAULT 'English',
    chapters JSONB NULL,
    cast_crew JSONB NULL,
    tags JSONB NULL,
    is_featured BOOLEAN NOT NULL DEFAULT FALSE,
    likes_count BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    CONSTRAINT projects_user_id_fk FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT projects_category_id_fk FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS projects_user_id_index ON projects (user_id);

-- Scripts
CREATE TABLE IF NOT EXISTS scripts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    project_id BIGINT NULL,
    title VARCHAR(255) NOT NULL DEFAULT 'Untitled Script',
    content JSONB NULL,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    CONSTRAINT scripts_user_id_fk FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT scripts_project_id_fk FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE SET NULL
);

-- Conversations
CREATE TABLE IF NOT EXISTS conversations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL DEFAULT 'New Conversation',
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    CONSTRAINT conversations_user_id_fk FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS conversation_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id BIGINT NOT NULL,
    sender VARCHAR(16) NOT NULL,
    body TEXT NOT NULL,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    CONSTRAINT conversation_messages_conversation_id_fk FOREIGN KEY (conversation_id) REFERENCES conversations(id) ON DELETE CASCADE,
    CONSTRAINT conversation_messages_sender_check CHECK (sender IN ('user', 'ai'))
);

-- Playlists
CREATE TABLE IF NOT EXISTS playlists (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT NULL,
    visibility VARCHAR(255) NOT NULL DEFAULT 'public',
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    CONSTRAINT playlists_user_id_fk FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS playlist_project (
    playlist_id BIGINT NOT NULL,
    project_id BIGINT NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY (playlist_id, project_id),
    CONSTRAINT playlist_project_playlist_id_fk FOREIGN KEY (playlist_id) REFERENCES playlists(id) ON DELETE CASCADE,
    CONSTRAINT playlist_project_project_id_fk FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE
);

-- Activity logs & moderation
CREATE TABLE IF NOT EXISTS activity_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NULL,
    action VARCHAR(255) NOT NULL,
    description TEXT NULL,
    category VARCHAR(255) NULL,
    ip_address VARCHAR(255) NULL,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    CONSTRAINT activity_logs_user_id_fk FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS activity_logs_category_index ON activity_logs (category);

CREATE TABLE IF NOT EXISTS content_flags (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    project_id BIGINT NOT NULL,
    reason TEXT NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'open',
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    CONSTRAINT content_flags_user_id_fk FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT content_flags_project_id_fk FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE,
    CONSTRAINT content_flags_status_check CHECK (status IN ('open','resolved','dismissed'))
);

-- Comments
CREATE TABLE IF NOT EXISTS comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    project_id BIGINT NOT NULL,
    parent_id BIGINT NULL,
    body TEXT NOT NULL,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    CONSTRAINT comments_user_id_fk FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT comments_project_id_fk FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE,
    CONSTRAINT comments_parent_id_fk FOREIGN KEY (parent_id) REFERENCES comments(id) ON DELETE SET NULL
);

-- Search history
CREATE TABLE IF NOT EXISTS search_histories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    query VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    CONSTRAINT search_histories_user_id_fk FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Likes
CREATE TABLE IF NOT EXISTS project_likes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    project_id BIGINT NOT NULL,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    CONSTRAINT project_likes_user_id_fk FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT project_likes_project_id_fk FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE,
    CONSTRAINT project_likes_user_project_unique UNIQUE (user_id, project_id)
);

-- Storage quotas/files
CREATE TABLE IF NOT EXISTS user_storage_quotas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    quota_bytes BIGINT NOT NULL DEFAULT 1073741824,
    used_bytes BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    CONSTRAINT user_storage_quotas_user_id_unique UNIQUE (user_id),
    CONSTRAINT user_storage_quotas_user_id_fk FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS user_files (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    path VARCHAR(255) NOT NULL,
    disk VARCHAR(255) NOT NULL DEFAULT 'digitalocean',
    mime_type VARCHAR(255) NULL,
    size_bytes BIGINT NOT NULL DEFAULT 0,
    type VARCHAR(16) NOT NULL DEFAULT 'other',
    folder VARCHAR(255) NULL,
    metadata JSONB NULL,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    CONSTRAINT user_files_user_id_fk FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT user_files_type_check CHECK (type IN ('document','image','video','audio','other'))
);

CREATE INDEX IF NOT EXISTS user_files_user_id_type_index ON user_files (user_id, type);
CREATE INDEX IF NOT EXISTS user_files_user_id_folder_index ON user_files (user_id, folder);

-- Editor
CREATE TABLE IF NOT EXISTS editor_projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    description TEXT NULL,
    thumbnail_path VARCHAR(255) NULL,
    timeline_data JSONB NULL,
    settings JSONB NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'draft',
    export_path VARCHAR(255) NULL,
    duration_seconds INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    CONSTRAINT editor_projects_user_id_fk FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT editor_projects_status_check CHECK (status IN ('draft','rendering','completed','failed'))
);

CREATE INDEX IF NOT EXISTS editor_projects_user_id_status_index ON editor_projects (user_id, status);

CREATE TABLE IF NOT EXISTS editor_project_assets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    editor_project_id BIGINT NOT NULL,
    user_file_id BIGINT NULL,
    name VARCHAR(255) NOT NULL,
    path VARCHAR(255) NOT NULL,
    type VARCHAR(255) NOT NULL,
    size_bytes BIGINT NOT NULL DEFAULT 0,
    duration_ms INTEGER NULL,
    width INTEGER NULL,
    height INTEGER NULL,
    metadata JSONB NULL,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    CONSTRAINT editor_project_assets_editor_project_id_fk FOREIGN KEY (editor_project_id) REFERENCES editor_projects(id) ON DELETE CASCADE,
    CONSTRAINT editor_project_assets_user_file_id_fk FOREIGN KEY (user_file_id) REFERENCES user_files(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS editor_project_assets_editor_project_id_index ON editor_project_assets (editor_project_id);

-- Notifications
CREATE TABLE IF NOT EXISTS notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    type VARCHAR(255) NOT NULL,
    title VARCHAR(255) NOT NULL,
    message TEXT NULL,
    icon VARCHAR(255) NULL,
    link VARCHAR(255) NULL,
    notifiable_type VARCHAR(255) NOT NULL,
    notifiable_id BIGINT NOT NULL,
    actor_id BIGINT NULL,
    data JSONB NULL,
    read_at TIMESTAMP NULL,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    CONSTRAINT notifications_user_id_fk FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT notifications_actor_id_fk FOREIGN KEY (actor_id) REFERENCES users(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS notifications_notifiable_type_notifiable_id_index
    ON notifications (notifiable_type, notifiable_id);

CREATE INDEX IF NOT EXISTS notifications_user_id_read_at_index ON notifications (user_id, read_at);
CREATE INDEX IF NOT EXISTS notifications_user_id_created_at_index ON notifications (user_id, created_at);

-- User settings
CREATE TABLE IF NOT EXISTS user_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,

    notify_likes BOOLEAN NOT NULL DEFAULT TRUE,
    notify_comments BOOLEAN NOT NULL DEFAULT TRUE,
    notify_follows BOOLEAN NOT NULL DEFAULT TRUE,
    notify_mentions BOOLEAN NOT NULL DEFAULT TRUE,
    notify_messages BOOLEAN NOT NULL DEFAULT TRUE,
    notify_project_updates BOOLEAN NOT NULL DEFAULT TRUE,
    notify_system BOOLEAN NOT NULL DEFAULT TRUE,
    email_notifications BOOLEAN NOT NULL DEFAULT FALSE,
    push_notifications BOOLEAN NOT NULL DEFAULT TRUE,
    digest_frequency VARCHAR(255) NOT NULL DEFAULT 'daily',

    profile_visibility VARCHAR(16) NOT NULL DEFAULT 'public',
    show_email BOOLEAN NOT NULL DEFAULT FALSE,
    show_social_links BOOLEAN NOT NULL DEFAULT TRUE,
    allow_messages BOOLEAN NOT NULL DEFAULT TRUE,
    show_activity BOOLEAN NOT NULL DEFAULT TRUE,
    show_online_status BOOLEAN NOT NULL DEFAULT TRUE,

    theme VARCHAR(255) NOT NULL DEFAULT 'dark',
    language VARCHAR(16) NOT NULL DEFAULT 'en',
    accent_color VARCHAR(255) NOT NULL DEFAULT 'amber',
    reduce_motion BOOLEAN NOT NULL DEFAULT FALSE,
    reduced_motion BOOLEAN NOT NULL DEFAULT FALSE,

    autoplay BOOLEAN NOT NULL DEFAULT TRUE,
    default_quality VARCHAR(255) NOT NULL DEFAULT 'auto',
    theater_mode BOOLEAN NOT NULL DEFAULT FALSE,
    playback_speed VARCHAR(16) NOT NULL DEFAULT '1',

    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,

    CONSTRAINT user_settings_user_id_unique UNIQUE (user_id),
    CONSTRAINT user_settings_user_id_fk FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT user_settings_profile_visibility_check CHECK (profile_visibility IN ('public','followers','private'))
);

-- Follows
CREATE TABLE IF NOT EXISTS follows (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    follower_id BIGINT NOT NULL,
    following_id BIGINT NOT NULL,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    CONSTRAINT follows_follower_id_fk FOREIGN KEY (follower_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT follows_following_id_fk FOREIGN KEY (following_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT follows_follower_following_unique UNIQUE (follower_id, following_id)
);

CREATE INDEX IF NOT EXISTS follows_following_id_index ON follows (following_id);

-- Site visits
CREATE TABLE IF NOT EXISTS site_visits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ip_address VARCHAR(45) NULL,
    user_agent VARCHAR(255) NULL,
    page VARCHAR(255) NULL,
    referrer VARCHAR(255) NULL,
    country VARCHAR(100) NULL,
    city VARCHAR(100) NULL,
    user_id BIGINT NULL,
    visit_date DATE NOT NULL,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    CONSTRAINT site_visits_user_id_fk FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS site_visits_visit_date_index ON site_visits (visit_date);
CREATE INDEX IF NOT EXISTS site_visits_ip_address_visit_date_index ON site_visits (ip_address, visit_date);

COMMIT;
